name: MinecraftBingo
version: 1.6.0
main: com.extremelyd1.main.Bingo
author: Extremelyd1
api-version: 1.17

commands:
  team:
    description: Command for handling teams
    usage: /<command> <random|add|remove>

  start:
    description: Command to start the game
    usage: /<command>

  end:
    description: Command to forcefully end the game
    usage: /<command>

  bingo:
    description: Command to output items left/collected on bingo card
    usage: /<command>

  card:
    description: Command to get a new bingo card if lost
    usage: /<command>

  pvp:
    description: Command to toggle PVP
    usage: /<command>

  maintenance:
    description: Command to toggle maintenance mode
    usage: /<command>

  wincondition:
    aliases: [wincon]
    description: Command to change win conditions, such as enabling full card mode
    usage: /<command> <full|lines|lockout> [argument]

  reroll:
    description: Command to reroll the bingo card
    usage: /<command>

  itemdistribution:
    aliases: [itemdist, distribution, dist]
    description: Command to change the item distribution
    usage: /<command> <S> <A> <B> <C> <D>

  timer:
    description: Command to set the max timer length
    usage: /<command> <enable|disable|length>

  coordinates:
    aliases: [coord, coords]
    description: Command to send your coordinates to your teammates
    usage: /<command>

  all:
    aliases: [a, g, global]
    description: Command to send a message to all players
    usage: /<command> <message>

  teamchat:
    aliases: [tc]
    description: Send a message to your team only
    usage: /<command> <message>

  test:
    description: Command to test a new feature
    usage: /<command>

  channel:
    aliases: [c]
    description: Change between default chat channels
    usage: /<command> <team|global>

  join:
    description: Join a team
    usage: /<command> <team name>

  generate:
    aliases: [worlds, gen]
    description: Pre-generate worlds
    usage: /<command> stop | <start> <numWorlds>

  tpt:
    description: Teleport to a member of your team
    usage: /<command>

  back:
    description: Teleport to your last death location
    usage: /<command>